# Generated by Django 3.2.6 on 2021-08-11 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('u_app', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
